spring.application.name=parentSchool

# Database Configuration - PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/parent_scdbs}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1985}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Multipart file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# MinIO Configuration
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:admin}
minio.secret-key=${MINIO_SECRET_KEY:password123}
minio.bucket-name=${MINIO_BUCKET_NAME:parentschool-files}

# Thymeleaf Configuration
spring.thymeleaf.cache=false

# JWT Configuration
jwt.secret.key=b9f867ca6f7f9b081f154de73bff0791ca3dc4841c77e8d09399cc268b9c47f1e12cb658c380733b0b805545920cc4ffed2418c60ec4df9409ed0536eb333e7e
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tjtrack268@gmail.com
spring.mail.password=tadr hvce kjal jfjm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.from=tjtrack268@gmail.com
